#!/usr/bin/env python3
"""Turn the supplied company logos into alpha masks for the software reel.

The reel paints a viewport-fixed gradient through each logo's alpha, the same
way the text version painted it through the glyphs. That needs the alpha to be
a clean silhouette, trimmed and consistently scaled — the originals carry very
different padding (MATLAB's ink is 44% of its canvas) and one is 3840px wide
for something that renders at about 50.

Colour is discarded by design: the mask only uses the alpha channel, so each
logo picks up the panel's own dim/accent ramp instead of introducing a fourth,
fifth and sixth colour.

    python tools/build-logo-masks.py
"""

import base64
import io
import os
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "images", "company-logos")
OUT = os.path.join(SRC, "masks")
HTML = os.path.join(ROOT, "index.html")

MASK_H = 180          # plenty for a ~50px render on a 3x display

# source filename → (slug, label, knockout_light)
#
# `knockout_light` is for logos whose alpha is a solid block. Fusion's and
# AutoCAD's icons are ~97% opaque tiles with a white glyph sitting on them, so
# their alpha alone silhouettes to a featureless slab; knocking out the
# near-white pixels recovers the letterform.
#
# Deliberately NOT set for Python: 41% of its opaque pixels read as "light",
# but that is the yellow snake, and knocking it out would delete half the mark.
LOGOS = [
    ("solidworks.png",        "solidworks", "SolidWorks", False),
    ("fusion360.png",            "fusion360",  "Fusion 360", True),
    ("autocad.webp",  "autocad",    "AutoCAD",    True),
    ("matlab.png",            "matlab",     "MATLAB",     False),
    ("python.webp",           "python",     "Python",     False),
]
LIGHT_CUTOFF = 210          # luminance above this counts as "the paper showing"

# Every logo here is a horizontal lockup — icon on the left, wordmark on the
# right — and the wordmark is what the reel is actually asking you to read: the
# items stand in for words in the sentence the lead phrase starts. Sizing them
# all to one lockup height therefore sets the *type* at wildly different sizes,
# because the wordmark is only a third of AutoCAD's lockup but nearly half of
# MATLAB's. So the mask stays a uniform MASK_H tall (one --ar formula, no
# resampling loss) and the generator emits a per-logo --logo-h instead, scaled
# so every wordmark lands at the same x-height.
LOGO_H_MAX = 1.15           # em, for the logo whose wordmark is smallest in its
                            # lockup — i.e. the largest any logo gets.
XBLEND = 0.6                # ...but only 60% of the way there. A solid icon
                            # tile carries far more optical mass than a thin
                            # wordmark, so correcting the full distance let
                            # Fusion's F and AutoCAD's A — the two lockups with
                            # the smallest wordmarks and therefore the biggest
                            # tiles — dominate the reel. 1.0 matches x-heights
                            # exactly; 0 reverts to one shared lockup height.
XBAND = 0.5                 # rows carrying >= this share of the peak row's ink
                            # are the wordmark's x-height band

# The page gets the masks inlined as data: URIs rather than as links to the
# files written beside this script. mask-image is a CORS-restricted resource,
# and Chrome gives every file:// document its own opaque origin — so a mask
# loaded from disk is cross-origin to a page opened from disk, Chrome drops it,
# and an element with a dropped mask paints nothing at all. The reel therefore
# vanished completely on file://, which is how this site is usually opened,
# while working perfectly over http. A data: URI is same-origin by definition.
#
# The PNGs are still written: they are what you open to see what a mask looks
# like, and they are what the measurements above run on.
ALPHA_BITS = 6              # quantising alpha to 64 levels is invisible on an
                            # anti-aliased silhouette and cuts the inlined
                            # payload by 36%
MARK_BEGIN = "    /* ══ masks: generated by tools/build-logo-masks.py ══ */\n"
MARK_END = "    /* ══ end masks ══ */\n"


def wordmark_fraction(im):
    """Share of the mask's height taken by the wordmark's x-height band.

    The lockup is split at its widest internal column gap — the space between
    the icon and the wordmark — and only the right-hand side is measured. The
    band is thresholded off the peak row rather than taken as the full extent,
    so ascenders and descenders do not count: Python's 'py' descenders alone
    read as 81% of its lockup, against a 38% x-height.
    """
    w, h = im.size
    px = list(im.getchannel("A").getdata())

    cols = [x for x in range(w) if any(px[y * w + x] > 90 for y in range(h))]
    gap, x0, prev = 0, 0, cols[0]
    for c in cols[1:]:
        if c - prev > gap:
            gap, x0 = c - prev, c
        prev = c

    prof = [sum(px[y * w + x] for x in range(x0, w)) for y in range(h)]
    cut = max(prof) * XBAND
    band = [y for y, v in enumerate(prof) if v >= cut]
    return (band[-1] - band[0] + 1) / h


def data_uri(im):
    """The mask as a base64 PNG, greyscale+alpha and quantised.

    Only the alpha is read by mask-image, so the colour channel collapses to
    one flat plane: LA instead of RGBA is a third off before quantising.
    """
    shift = 8 - ALPHA_BITS
    a = im.getchannel("A").point(lambda v: (v >> shift) << shift)
    la = Image.merge("LA", (Image.new("L", im.size, 0), a))
    buf = io.BytesIO()
    la.save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


def write_css(rules):
    """Splice the generated rules into index.html, between the markers."""
    src = open(HTML, encoding="utf-8").read()
    i, j = src.index(MARK_BEGIN), src.index(MARK_END)
    out = src[:i] + MARK_BEGIN + "".join(rules) + src[j:]
    open(HTML, "w", encoding="utf-8", newline="\n").write(out)
    return len(out) - len(src)


def build():
    os.makedirs(OUT, exist_ok=True)
    rows = []
    for fname, slug, label, knockout in LOGOS:
        path = os.path.join(SRC, fname)
        if not os.path.exists(path):
            print("  MISSING  " + fname)
            continue

        im = Image.open(path).convert("RGBA")
        im = im.crop(im.getchannel("A").getbbox())          # trim to the ink

        if knockout:
            lum = im.convert("L")
            a = im.getchannel("A")
            knocked = Image.new("L", im.size)
            knocked.putdata([0 if (al > 8 and l > LIGHT_CUTOFF) else al
                             for al, l in zip(a.getdata(), lum.getdata())])
            im.putalpha(knocked)

        ratio = MASK_H / im.height
        im = im.resize((max(1, round(im.width * ratio)), MASK_H), Image.LANCZOS)

        # Keep only the alpha. The mask is painted by the page, so the RGB the
        # logo happened to ship with is irrelevant — and dropping it also drops
        # the brand colours we are deliberately not using.
        mask = Image.new("RGBA", im.size, (0, 0, 0, 0))
        mask.putalpha(im.getchannel("A"))
        mask.save(os.path.join(OUT, slug + ".png"), "PNG", optimize=True)

        rows.append([slug, label, im.width / im.height,
                     wordmark_fraction(mask), 0.0, data_uri(mask)])

    if not rows:
        return

    # Smallest wordmark-in-lockup gets the tallest render; the rest scale down
    # from it so all five wordmarks come out the same size.
    smallest = min(r[3] for r in rows)
    for r in rows:
        r[4] = LOGO_H_MAX * (smallest / r[3]) ** XBLEND

    width = max(len(r[0]) for r in rows)
    rules = ["    .lg-%s{--ar:%.3f;--logo-h:%.3fem;--logo:url('%s');}\n"
             % (slug.ljust(width), ar, lh, uri)
             for slug, label, ar, frac, lh, uri in rows]
    delta = write_css(rules)

    print("  %-12s %-12s %-7s %-7s %-7s %s"
          % ("slug", "label", "aspect", "wordmk", "logo-h", "inlined"))
    for slug, label, ar, frac, lh, uri in rows:
        print("  %-12s %-12s %-7.3f %-7.0f %-7.3f %.1fK"
              % (slug, label, ar, frac * 100, lh, len(uri) / 1024))
    print("\n  index.html %+.1fK" % (delta / 1024))


if __name__ == "__main__":
    build()
